apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-catalog-cicd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: product-catalog
  source:
    path: manifests/pipelines/overlays/registry
    repoURL: https://github.com/gnunn-gitops/product-catalog.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
  ignoreDifferences:
  - group: build.openshift.io
    kind: BuildConfig
    jsonPointers:
    - /status
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: apps.openshift.io
    kind: DeploymentConfig
    jsonPointers:
    - /spec/replicas
  - group: route.openshift.io
    kind: Route
    jsonPointers:
    - /status/ingress
  - group: tekton.dev/v1alpha1
    kind: PipelineRun
  sync:
    comparedTo:
      destination:
        namespace: argocd
        server: https://kubernetes.default.svc
      source:
        path: manifests/pipelines/overlays/registry
        repoURL: https://github.com/gnunn-gitops/product-catalog.git
        targetRevision: master