apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: product-catalog-cicd

bases:
- ../../base
# Nexus
- github.com/redhat-canada-gitops/catalog//nexus2/base
# Sonarqube
- github.com/redhat-canada-gitops/catalog//sonarqube8/overlays/plugins

# resources:
# - namespace.yaml