apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana
  argocd.argoproj.io/sync-wave: "0"
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: grafana-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: grafana-operator.v2.0.0