apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: prometheus
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  channel: beta
  installPlanApproval: Automatic
  name: prometheus
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: prometheusoperator.0.32.0