apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: Project for deploying the quarkus server application as a native version
    openshift.io/display-name:  Product Catalog Native
  labels:
    size: medium
  name: product-catalog-native