apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: server
  annotations:
    app.openshift.io/connects-to: database
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: 'https://github.com/gnunn-gitops/product-catalog-server'
  labels:
    app: server
    app.kubernetes.io/name: server
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: server
    app.openshift.io/runtime: quarkus
    app.kubernetes.io/part-of: product-catalog
spec:
  template:
    metadata:
      annotations:
        app.openshift.io/connects-to: database
        app.openshift.io/vcs-ref: master
        app.openshift.io/vcs-uri: 'https://github.com/gnunn-gitops/product-catalog-server'
      labels:
        app: server
        app.kubernetes.io/name: server
        app.kubernetes.io/component: backend
        app.kubernetes.io/instance: server
        app.openshift.io/runtime: quarkus
        app.kubernetes.io/part-of: product-catalog
    spec:
      containers:
        - image: quay.io/gnunn/server-native:latest
          env:
            - name: QUARKUS_KUBERNETES_CONFIG_ENABLED
              value: "true"
            - name: QUARKUS_KUBERNETES_CONFIG_CONFIG_MAPS
              value: server
            - name: CORS_ORIGIN
              value: "*"
