apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../../environments/overlays/argocd

patchesJson6902:
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: product-catalog-dev
  path: patch-dev-app.yaml

- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: product-catalog-test
  path: patch-test-app.yaml

- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: product-catalog-prod
  path: patch-prod-app.yaml