apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: product-catalog

# generatorOptions:
#   disableNameSuffixHash: true

# secretGenerator:
#   - name: dest-docker-config
#     type: kubernetes.io/dockerconfigjson
#     files:
#       - secrets/.dockerconfigjson

bases:
- ../../../manifests/app/base
- github.com/redhat-canada-gitops/catalog//apicast/overlays/default

resources:
- namespace.yaml
- user-rolebinding.yaml
- api-url-config-sealed-secret.yaml

patchesStrategicMerge:
- patch.yaml

transformers:
    - global-labels.yaml