apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-catalog-manager
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: apps-product-catalog
  source:
    path: environments/overlays/tools/argocd/apps
    repoURL: https://github.com/gnunn-gitops/product-catalog.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: false
      selfHeal: false