apiVersion: v1
kind: Secret
metadata:
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  name: maven-repo-creds
type: Opaque
data:
  username: YWRtaW4K
  password: YWRtaW4xMjMK