apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: product-catalog-serverless

bases:
- ../../../manifests/app/database/base
- ../../../manifests/app/server-serverless/base
- ../../../manifests/app/client/base

resources:
- namespace.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: client
  path: patch-client-deployment.yaml