apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: maven-settings
    files:
      - config/settings.xml
  - name: newman-env
    files:
      - config/newman-dev-env.json
      - config/newman-test-env.json

resources:
- secrets/maven-repo-creds.yaml
# Server pipeline
- server-imagestream.yaml
- server-buildconfig.yaml
- server-pvc.yaml
- server-pipeline.yaml