apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    operated-prometheus: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  name: prometheus-operated
spec:
  port:
    targetPort: web
  to:
    kind: Service
    name: prometheus-operated
    weight: 100
  wildcardPolicy: None