apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: client
spec:
  workspaces:
    - name: git-source
  params:
    - name: git_revision
      type: string
      default: master
    - name: git_url
      type: string
      default: https://github.com/gnunn-gitops/product-catalog-client
    - name: image_dest_url
      type: string
      description: External registry location to copy image to
      default: quay.io/gnunn/client
  tasks:
    - name: clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: git-source
      params:
        - name: url
          value: "$(params.git_url)"
        - name: revision
          value: "$(params.git_revision)"
        - name: deleteExisting
          value: "true"
    - name: build
      taskRef:
        name: npm
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: git-source
    - name: quality
      taskRef:
        name: npm-quality
      runAfter:
        - build
      workspaces:
        - name: source
          workspace: git-source
    - name: build-image
      taskRef:
        name: binary-s2i
      workspaces:
        - name: source
          workspace: git-source
      runAfter:
        - quality
      params:
        - name: directory
          value: "$(workspaces.source.path)/dist"
        - name: buildconfig
          value: client
    - name: promote-image
      taskRef:
        name: push-image
        kind: Task
      runAfter:
        - build-image
      params:
        - name: src-image
          value: image-registry.openshift-image-registry.svc:5000/product-catalog-cicd/client:latest
        - name: dest-image
          value: $(params.image_dest_url)
        - name: dest-additional-tag
          value: $(tasks.clone.results.commit)
    - name: deploy-dev
      taskRef:
        name: deploy
        kind: Task
      runAfter:
        - promote-image
      params:
        - name: NAME
          value: client
        - name: NAMESPACE
          value: product-catalog-dev
    - name: deploy-test
      taskRef:
        name: deploy
        kind: Task
      runAfter:
        - deploy-dev
      params:
        - name: NAME
          value: client
        - name: NAMESPACE
          value: product-catalog-test