apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: maven-settings
    files:
      - configs/settings.xml
  - name: newman-env
    files:
      - configs/newman-dev-env.json
      - configs/newman-test-env.json

resources:
- secrets/maven-repo-creds.yaml
# Nexus
# - github.com/redhat-canada-gitops/catalog//nexus2/base
# Sonarqube
# - github.com/redhat-canada-gitops/catalog//sonarqube8/overlays/plugins
# Supporting infra
- m2-cache-pvc.yaml
- npm-cache-pvc.yaml
- dependency-cache-pvc.yaml
# Tekton tasks
- task-maven.yaml
- task-npm.yaml
- task-npm-quality.yaml
- task-binary-s2i.yaml
- task-push-image.yaml
- task-deploy.yaml
- task-newman.yaml
- task-patch-image-tag-pr.yaml
- condition-push-image.yaml
# Server pipeline
- server-imagestream.yaml
- server-buildconfig.yaml
- server-pvc.yaml
- server-pipeline.yaml
# Client pipeline
- client-imagestream.yaml
- client-buildconfig.yaml
- client-pvc.yaml
- client-pipeline.yaml