apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: server
spec:
  workspaces:
    - name: git-source
  params:
    - name: git_revision
      type: string
      default: master
    - name: git_url
      type: string
      default: https://github.com/gnunn-gitops/product-catalog-server
    - name: MAVEN_MIRROR_URL
      default: ""
    - name: image_dest_url
      type: string
      description: External registry location to copy image to
      default: quay.io/gnunn/server
  tasks:
    - name: clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      workspaces:
        - name: output
          workspace: git-source
      params:
        - name: url
          value: "$(params.git_url)"
        - name: revision
          value: "$(params.git_revision)"
        - name: deleteExisting
          value: "true"
    - name: build
      taskRef:
        name: maven
      workspaces:
        - name: source
          workspace: git-source
      runAfter:
        - clone
      params:
        - name: MAVEN_MIRROR_URL
          value: "$(params.MAVEN_MIRROR_URL)"
        - name: GOALS
          value: "package sonar:sonar install deploy"
        - name: PROFILES
          value: "quality,copy"
    - name: build-image
      taskRef:
        name: binary-s2i
      workspaces:
        - name: source
          workspace: git-source
      runAfter:
        - build
      params:
        - name: file
          value: "$(workspaces.source.path)/target/*-runner.jar"
        - name: buildconfig
          value: server
    - name: promote-image
      taskRef:
        name: push-image
      runAfter:
        - build-image
      params:
        - name: src-image
          value: image-registry.openshift-image-registry.svc:5000/product-catalog-cicd/server:latest
        - name: dest-image
          value: $(params.image_dest_url)
        - name: dest-additional-tag
          value: $(tasks.clone.results.commit)
    - name: deploy-dev
      taskRef:
        name: deploy
      runAfter:
        - promote-image
      params:
        - name: NAME
          value: server
        - name: NAMESPACE
          value: product-catalog-dev
    - name: dev-test
      taskRef:
        name: newman
      runAfter:
        - deploy-dev
      params:
        - name: COLLECTION
          value: https://raw.githubusercontent.com/gnunn-gitops/product-catalog-server/master/tests/product-catalog-server-tests.json
        - name: ENVIRONMENT
          value: newman-dev-env.json
    - name: deploy-test
      taskRef:
        name: deploy
      runAfter:
        - dev-test
      params:
        - name: NAME
          value: server
        - name: NAMESPACE
          value: product-catalog-test
    - name: test-test
      taskRef:
        name: newman
      runAfter:
        - deploy-test
      params:
        - name: COLLECTION
          value: https://raw.githubusercontent.com/gnunn-gitops/product-catalog-server/master/tests/product-catalog-server-tests.json
        - name: ENVIRONMENT
          value: newman-test-env.json
