apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: npm
spec:
  workspaces:
  - name: app-binary
  inputs:
    resources:
      - name: source
        type: git
  # results:
  #   - name: short-git-commit-id
  #     description: The short commit id from git
  steps:
    - name: npm-install
      image: quay.io/gnunn/nodejs10-tools:latest
      command:
        - /bin/sh
        - -c
      args:
        - npm install --package-lock
      workingDir: /workspace/source
      volumeMounts:
        - name: npm-cache
          mountPath: /workspace/source/node_modules
    - name: build
      image: quay.io/gnunn/nodejs10-tools:latest
      command:
        - /bin/sh
        - -c
      args:
        - npm run build
      workingDir: /workspace/source
      volumeMounts:
        - name: npm-cache
          mountPath: /workspace/source/node_modules
    - name: quality
      image: quay.io/gnunn/nodejs10-tools:latest
      command:
        - /bin/sh
        - -c
      args:
        -  |-
          echo "Performing quality check"
          mkdir -p coverage
          mkdir -p reports/dependency-check
          dependency-check.sh --format ALL -s . --out reports/dependency-check --project "product-catalog-client"
          npm run sonar
          echo "Quality check complete, see results in sonarqube"
      workingDir: /workspace/source
      volumeMounts:
        - name: npm-cache
          mountPath: /workspace/source/node_modules
        - name: dependency-cache
          mountPath: /opt/dependency-check/data
    - name: copy-dist
      image: quay.io/gnunn/nodejs10-tools:latest
      command:
        - /bin/sh
        - -c
      args:
        - cp -R ./dist/* $(workspaces.app-binary.path)
      workingDir: /workspace/source
    - name: save-commit-sha
      image: docker.io/maven:3.6.3-jdk-8
      command:
        - '/bin/bash'
        - '-c'
      args:
        - |-
          mkdir -p $(workspaces.app-binary.path)/git-sha
          git rev-parse --short HEAD | tee $(workspaces.app-binary.path)/git-sha/commit-id
      workingDir: /workspace/source
    # - name: output-result
    #   image: quay.io/gnunn/nodejs10-tools:latest
    #   command:
    #     - /bin/sh
    #     - -c
    #   args:
    #     - git rev-parse --short HEAD | tee $(results.short-git-commit-id.path)
    #   workingDir: /workspace/source
  volumes:
    - name: npm-cache
      persistentVolumeClaim:
        claimName: npm-cache
    - name: dependency-cache
      persistentVolumeClaim:
        claimName: dependency-cache