apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: patch-image-tag-and-pr
spec:
  params:
  - name: src-tag
    type: string
    default: latest
    description: The source tag in the file to replace
  - name: dest-tag
    type: string
    description: The new tag to replace it with
  - name: filename
    type: string
    description: The filename in which to update the tag
  - name: review-links
    type: string
    default: ""
    description: A list of links that should be reviewed prior to approving PR
  - name: github-secret
    type: string
    default: github
    description: "The name of the secret that has your github username and token"
  steps:
    - name: run-commands
      image: quay.io/gnunn/github-hub:latest
      script: |
        #!/usr/bin/env bash

        echo "Creating new branch 'push-$(params.dest-tag)'"

        # Create new branch
        git checkout -b "push-$(params.dest-tag)" --track origin/master

        ls -l

        ls $(params.filename)

        # Replace image tag
        sed -i -e 's/:$(params.src-tag)/:$(params.dest-tag)/g' $(params.filename)

        git commit -m "Production image update to $(params.dest-tag)"

        hub pull-request -m "Update image to $(params.dest-tag)" -m "$(params.review-links)"
      env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: $(params.github-secret)
              key: password
        - name: GITHUB_USER
          valueFrom:
            secretKeyRef:
              name: $(params.github-secret)
              key: username
