apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: openshift-client
spec:
  workspaces:
  - name: app-binary
  params:
    - name: COMMANDS
      type: string
  steps:
    - name: run-commands
      image: quay.io/openshift/origin-cli:latest
      script: |
        #!/usr/bin/env bash
        $(inputs.params.COMMANDS)