apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: newman
spec:
  inputs:
    params:
    - name: COLLECTIONS
      description: The URL of the collections test to run
      type: string
    - name: ENVIRONMENT
      description: The environment file to use from the newman-env configmap
      default: "newman-env.json"
  steps:
    - name: collections-test
      image: docker.io/postman/newman:latest
      command:
        - newman
      args:
        - run
        - $(inputs.params.COLLECTIONS)
        - -e
        - /config/$(inputs.params.ENVIRONMENT)
        - --bail
      volumeMounts:
        - name: newman-env
          mountPath: /config
  volumes:
    - name: newman-env
      configMap:
        name: newman-env