---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: server
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: master
  - name: gitrepositoryurl
    description: The git repository url
  - name: message
    description: The message to print
    default: This is the default message
  - name: contenttype
    description: The Content-Type of the event
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
      labels:
        tekton.dev/pipeline: server
      generateName: server-webhook-
    spec:
      pipelineRef:
        name: server
      resources:
        - name: source
          resourceRef:
            name: server
      params:
        - name: MAVEN_MIRROR_URL
          value: http://nexus:8081/content/groups/public/
      workspaces:
      - name: app-binary
        persistentVolumeClaim:
          claimName: server-binary