apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/part-of: product-catalog

configMapGenerator:
- name: server
  files:
    - configs/application.properties
- name: client
  files:
    - configs/config.js
- name: productdb-init
  files:
    - configs/90-init-database.sh
    - configs/import.sql
    - configs/schema.sql

resources:
  - db-pvc.yaml
  - db-secret.yaml
  - db-service.yaml
  - db-deployment.yaml
  - server-service.yaml
  - server-route.yaml
  - server-deployment.yaml
  - client-service.yaml
  - client-route.yaml
  - client-deployment.yaml