apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../manifests/tools/argocd/base

namespace: argocd

resources:
- product-catalog-project.yaml

patchesJson6902:
- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: product-catalog-dev
  path: patch-project.yaml

- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: product-catalog-test
  path: patch-project.yaml

- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: product-catalog-prod
  path: patch-project.yaml

- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: product-catalog-monitor-operators
  path: patch-project.yaml

- target:
    group: argoproj.io
    version: v1alpha1
    kind: Application
    name: product-catalog-monitor-metrics
  path: patch-project.yaml
