apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: product-catalog-monitor

commonAnnotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

bases:
- https://github.com/redhat-canada-gitops/catalog/prometheus-operator/overlays/aggregate
- https://github.com/redhat-canada-gitops/catalog/grafana-operator/overlays/aggregate
- ../../../manifests/app/monitor/base

resources:
- namespace.yaml

patchesStrategicMerge:
- sm-patch.yaml

patchesJson6902:
- target:
    version: v1
    group: operators.coreos.com
    kind: OperatorGroup
    name: app-prometheus
  path: patch-operator-group.yaml
- target:
    version: v1
    group: operators.coreos.com
    kind: OperatorGroup
    name: grafana
  path: patch-operator-group.yaml
- target:
    version: v1
    group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
    name: grafana-proxy
  path: patch-proxy-namespace.yaml