---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: server
spec:
  serviceAccountName: pipeline
  triggers:
    - name: server-webhook
      bindings:
        - name: github-triggerbinding
      template:
        name: server
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: server-webhook
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: server
spec:
  port:
    targetPort: 8080
  to:
    kind: "Service"
    name: el-server
    weight: 100