apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-proxy
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-proxy
roleRef:
  name: prometheus-proxy
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: product-catalog-monitor
userNames:
  - system:serviceaccount:product-catalog-monitor:prometheus-k8s