apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: quarkus
spec:
  selector:
    matchLabels:
      quarkus-prometheus: "true"
  endpoints:
  - port: http
    path: /metrics
    scheme: http