apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: prometheus
spec:
  # alerting:
  #   alertmanagers:
  #     - name: alertmanager-main
  #       namespace: openshift-monitoring
  #       port: web
  replicas: 1
  ruleSelector: {}
  securityContext: {}
  serviceAccountName: prometheus-k8s
  serviceMonitorSelector: {}

  # Attempt to get oauth working
  # containers:
  #   - args:
  #       - '-provider=openshift'
  #       - '-pass-basic-auth=false'
  #       - '-https-address=:9091'
  #       - '-http-address='
  #       - '-email-domain=*'
  #       - '-upstream=http://localhost:9090'
  #       - '-openshift-sar={"resource": "namespaces", "verb": "get"}'
  #       - '-openshift-delegate-urls={"/": {"resource": "namespaces", "verb": "get"}}'
  #       - '-tls-cert=/etc/tls/private/tls.crt'
  #       - '-tls-key=/etc/tls/private/tls.key'
  #       - '-client-secret-file=/var/run/secrets/kubernetes.io/serviceaccount/token'
  #       - '-cookie-secret-file=/etc/proxy/secrets/session_secret'
  #       - '-openshift-service-account=prometheus-k8s'
  #       - '-openshift-ca=/etc/pki/tls/cert.pem'
  #       - '-openshift-ca=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt'
  #       - '-openshift-ca=/etc/grafana-configmaps/ocp-injected-certs/ca-bundle.crt'
  #       - '-skip-auth-regex=^/metrics'
  #     image: 'quay.io/openshift/origin-oauth-proxy:4.5'
  #     name: prometheus-proxy
  #     ports:
  #       - containerPort: 9091
  #         name: prom-proxy
  #     resources: {}
  #     volumeMounts:
  #       - mountPath: /etc/tls/private
  #         name: secret-prometheus-k8s-tls
  #       - mountPath: /etc/proxy/secrets
  #         name: secret-prometheus-k8s-proxy
  # secrets:
  #   - prometheus-k8s-tls
  #   - prometheus-k8s-proxy
  # configMaps:
  #   - ocp-injected-certs

  # Old Grafana stuff
  # service:
  #   ports:
  #     - name: prometheus-proxy
  #       port: 9091
  #       protocol: TCP
  #       targetPort: prometheus-proxy
  #   annotations:
  #     service.alpha.openshift.io/serving-cert-secret-name: prometheus-k8s-tls
  # ingress:
  #   enabled: True
  #   targetPort: prometheus-proxy
  #   termination: reencrypt
  # client:
  #   preferService: True
  # serviceAccount:
  #   annotations:
  #     serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"prometheus-route"}}'