apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Prune=false
  name: client-push-prod-pr
  generateName: client-push-prod-pr-
spec:
  serviceAccountName: github-pipeline
  pipelineRef:
    name: push-prod-pr
  params:
    - name: image_dest_tag
      value: f022094-1251721310
    - name: image_dest_url
      value: quay.io/gnunn/client
    - name: cluster
      value: ocplab
    - name: app
      value: client
  workspaces:
  - name: git-source
    persistentVolumeClaim:
      claimName: manifest-source