apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: push-to-prod
spec:
  params:
  - name: push
    type: string
  check:
    image: registry.redhat.io/ubi8/ubi-minimal
    script: |
      #!/bin/sh
      if [ "$(params.push)" = "true" ]; then
        echo "Pushing to prod)"
        exit 0
      else
        echo "Not pushing to prod"
        exit 1
      fi